#ifndef Ajisai_configure_h
#define Ajisai_configure_h

#cmakedefine AJISAI_BUILD_STATIC

#cmakedefine AJISAI_TARGET_APPLE
#cmakedefine AJISAI_TARGET_IOS
#cmakedefine AJISAI_TARGET_IOS_SIMULATOR
#cmakedefine AJISAI_TARGET_UNIX
#cmakedefine AJISAI_TARGET_WINDOWS
#cmakedefine AJISAI_TARGET_WINDOWS_RT
#cmakedefine AJISAI_TARGET_EMSCRIPTEN
#cmakedefine AJISAI_TARGET_ANDROID

#endif